apiVersion: apps/v1
kind: Deployment
metadata:
  name: clj-lein-webapp-example
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clj-lein-webapp-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clj-lein-webapp-example
    spec:
      containers:
      - image: joakimen/clj-lein-webapp-example:0.2.0
        imagePullPolicy: Always
        name: clj-lein-webapp-example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
