name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Build
      run: lein uberjar

    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@v1

    - name: Lint src with clj-kondo
      uses: clj-kondo --lint src
